version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      # Best practice to use .env files or Docker secrets in real-world scenarios.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./task-manager-backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://root:123456@mongodb:27017/tasks?authSource=admin
    command: yarn start

  frontend:
    build:
      context: ./task-manager-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3001

volumes:
  mongo-data:
